# Generated by Django 2.1.3 on 2018-11-28 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kundennummer', models.IntegerField()),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.CharField(blank=True, max_length=20, null=True)),
                ('prozent', models.FloatField(default=0.0)),
                ('rechnungsanzahl', models.IntegerField(default=0)),
                ('dsgvo', models.BooleanField(default=False, help_text='Mitglied hat zur Datenschutzgrundverordnung zugestimmt.', verbose_name='Datenschutzgrundverordnung')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pobox', models.IntegerField(blank=True, null=True)),
                ('strasse', models.CharField(blank=True, max_length=100, null=True)),
                ('plz', models.CharField(blank=True, max_length=20, null=True)),
                ('ort', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anrede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anrede', models.CharField(max_length=100)),
                ('oldid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Beruf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beruf', models.CharField(max_length=100)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('oldid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid4', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bezahltam', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitgliedsnummer', models.IntegerField()),
                ('institution_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('name3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('beigz', models.CharField(blank=True, max_length=20, null=True)),
                ('beidat', models.DateField(blank=True, null=True)),
                ('storndat', models.DateField(blank=True, null=True)),
                ('versand', models.CharField(blank=True, max_length=20, null=True)),
                ('sub', models.CharField(blank=True, max_length=10, null=True)),
                ('heftanzahl', models.IntegerField(blank=True, default=0, null=True)),
                ('anmerkung', models.TextField(blank=True, null=True)),
                ('dsgvo', models.BooleanField(default=False, help_text='Mitglied hat zur Datenschutzgrundverordnung zugestimmt.', verbose_name='Datenschutzgrundverordnung')),
                ('berufsgruppe', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Beruf')),
            ],
        ),
        migrations.CreateModel(
            name='Kosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(max_length=3)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('betrag', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(max_length=100)),
                ('iso', models.CharField(max_length=4)),
                ('EU', models.BooleanField(default=True)),
                ('oldid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mitgliedsart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitart', models.CharField(max_length=3)),
                ('bezeichnung', models.CharField(max_length=100)),
                ('anmerkung', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='offenePosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateField(default=django.utils.timezone.now)),
                ('bezahltam', models.DateTimeField(blank=True, null=True)),
                ('offen', models.FloatField(blank=True, default=0, null=True)),
                ('zahlung', models.FloatField(blank=True, default=0, null=True)),
                ('bezahlt', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['erstellt'],
            },
        ),
        migrations.CreateModel(
            name='PasswortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkvalue', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vereins_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Titel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('oldid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VereinsMitglied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mitgliedsnummer', models.IntegerField()),
                ('anrede', models.CharField(blank=True, max_length=100, null=True)),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('vorname', models.CharField(blank=True, max_length=100, null=True)),
                ('nachname', models.CharField(blank=True, max_length=100, null=True)),
                ('surname2', models.CharField(blank=True, max_length=100, null=True)),
                ('surname3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('beigz', models.CharField(blank=True, max_length=20, null=True)),
                ('beidat', models.DateField(blank=True, null=True)),
                ('storndat', models.DateField(blank=True, null=True)),
                ('versand', models.CharField(blank=True, max_length=20, null=True)),
                ('gebdat', models.DateField(blank=True, null=True)),
                ('diplomdat', models.DateField(blank=True, null=True)),
                ('diplomort', models.CharField(blank=True, max_length=100, null=True)),
                ('sub', models.CharField(blank=True, max_length=10, null=True)),
                ('vortragold', models.CharField(blank=True, max_length=10, null=True)),
                ('heftanzahl', models.IntegerField(blank=True, default=0, null=True)),
                ('anmerkung', models.TextField(blank=True, null=True)),
                ('dsgvo', models.BooleanField(default=False, help_text='Mitglied hat zur Datenschutzgrundverordnung zugestimmt.', verbose_name='Datenschutzgrundverordnung')),
                ('berufsgruppe', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Beruf')),
                ('kostenart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Kosten')),
            ],
            options={
                'ordering': ['nachname'],
            },
        ),
        migrations.CreateModel(
            name='Versand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versand', models.CharField(max_length=3)),
                ('bezeichnung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vortragold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldid', models.IntegerField()),
                ('Vortragsort', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vortragsort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vortragsort', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AboHeft',
            fields=[
                ('adresse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mitglieder.Adresse')),
                ('abonummer', models.IntegerField()),
                ('anrede', models.CharField(blank=True, max_length=100, null=True)),
                ('titel', models.CharField(blank=True, max_length=100, null=True)),
                ('vorname', models.CharField(blank=True, max_length=100, null=True)),
                ('nachname', models.CharField(blank=True, max_length=100, null=True)),
                ('surname2', models.CharField(blank=True, max_length=100, null=True)),
                ('surname3', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=100, null=True)),
                ('heftanzahl', models.IntegerField(blank=True, default=0, null=True)),
                ('beigz', models.CharField(blank=True, max_length=20, null=True)),
                ('beidat', models.DateField(blank=True, null=True)),
                ('storndat', models.DateField(blank=True, null=True)),
                ('rueckstand', models.FloatField(default=0.0)),
                ('gutschrift', models.FloatField(default=0.0)),
                ('aboart', models.CharField(choices=[('DA', 'Dauerauftrag'), ('JB', 'Jahresbestellung')], default='DA', max_length=2)),
                ('aboanfang', models.DateField(blank=True, null=True)),
                ('aboende', models.DateField(blank=True, null=True)),
                ('anmerkung', models.TextField(blank=True, null=True)),
            ],
            bases=('mitglieder.adresse',),
        ),
        migrations.AddField(
            model_name='vereinsmitglied',
            name='lieferadresse',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', related_name='Zustelladresse', to='mitglieder.Adresse'),
        ),
        migrations.AddField(
            model_name='vereinsmitglied',
            name='mitgliedsart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Mitgliedsart'),
        ),
        migrations.AddField(
            model_name='vereinsmitglied',
            name='rechnungsadresse',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', related_name='Rechnungsadresse', to='mitglieder.Adresse'),
        ),
        migrations.AddField(
            model_name='vereinsmitglied',
            name='vortrag',
            field=models.ManyToManyField(to='mitglieder.Vortragsort'),
        ),
        migrations.AddField(
            model_name='vereinsmitglied',
            name='wohnadresse',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', related_name='Wohnadresse', to='mitglieder.Adresse'),
        ),
        migrations.AddField(
            model_name='offeneposten',
            name='mitglied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.VereinsMitglied'),
        ),
        migrations.AddField(
            model_name='institution',
            name='kostenart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Kosten'),
        ),
        migrations.AddField(
            model_name='institution',
            name='lieferadresse',
            field=models.ForeignKey(on_delete='models.DO_NOTHING', related_name='Zustelladresse2', to='mitglieder.Adresse'),
        ),
        migrations.AddField(
            model_name='institution',
            name='mitgliedsart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Mitgliedsart'),
        ),
        migrations.AddField(
            model_name='institution',
            name='rechnungsadresse',
            field=models.ForeignKey(on_delete='models.DO_NOTHING', related_name='Rechnungsadresse2', to='mitglieder.Adresse'),
        ),
        migrations.AddField(
            model_name='institution',
            name='vortrag',
            field=models.ManyToManyField(to='mitglieder.Vortragsort'),
        ),
        migrations.AddField(
            model_name='institution',
            name='wohnadresse',
            field=models.ForeignKey(on_delete='models.DO_NOTHING', related_name='Wohnadresse2', to='mitglieder.Adresse'),
        ),
        migrations.AddField(
            model_name='emailid',
            name='mitglied',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitglieder.VereinsMitglied'),
        ),
        migrations.AddField(
            model_name='emailid',
            name='offeneposten',
            field=models.ManyToManyField(to='mitglieder.offenePosten'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Land'),
        ),
        migrations.AddField(
            model_name='abonnent',
            name='rechnungsanschrift',
            field=models.ForeignKey(on_delete='models.DELETE', related_name='Anschrift', to='mitglieder.Adresse'),
        ),
        migrations.AddField(
            model_name='aboheft',
            name='kundennummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Abonnent'),
        ),
    ]
