# Generated by Django 2.1.3 on 2018-11-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereinsmitglied',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
