# Generated by Django 2.1.3 on 2018-12-02 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0002_vereinsmitglied_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beruf',
            options={'ordering': ['beruf']},
        ),
        migrations.AlterModelOptions(
            name='kosten',
            options={'ordering': ['art']},
        ),
        migrations.AlterModelOptions(
            name='mitgliedsart',
            options={'ordering': ['mitart']},
        ),
        migrations.AlterModelManagers(
            name='vereinsmitglied',
            managers=[
                ('aktive', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='berufsgruppe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Beruf'),
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='mitgliedsnummer',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='vortrag',
            field=models.ManyToManyField(blank=True, null=True, to='mitglieder.Vortragsort'),
        ),
    ]
