# Generated by Django 2.1.3 on 2018-12-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0003_auto_20181202_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='fax',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
