# Generated by Django 2.1.3 on 2018-12-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0004_auto_20181203_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vereinsmitglied',
            old_name='surname2',
            new_name='namenszusatz',
        ),
        migrations.RemoveField(
            model_name='vereinsmitglied',
            name='surname3',
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='beigz',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='sub',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
    ]
