# Generated by Django 2.1.3 on 2018-12-03 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0005_auto_20181203_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeneposten',
            name='erstellt',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
