# Generated by Django 2.1.3 on 2018-12-03 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0006_auto_20181203_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeneposten',
            name='mitglied',
            field=models.ForeignKey(default=4007, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.VereinsMitglied'),
            preserve_default=False,
        ),
    ]
