# Generated by Django 2.1.3 on 2018-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0007_auto_20181203_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeneposten',
            name='offen',
            field=models.FloatField(default=0),
        ),
    ]
