# Generated by Django 2.1.3 on 2018-12-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0008_auto_20181203_1449'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vereinsmitglied',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='abonnent',
            name='rechnungsanschrift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Anschrift', to='mitglieder.Adresse'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='lieferadresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Zustelladresse2', to='mitglieder.Adresse'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='rechnungsadresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rechnungsadresse2', to='mitglieder.Adresse'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='wohnadresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Wohnadresse2', to='mitglieder.Adresse'),
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='lieferadresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Zustelladresse', to='mitglieder.Adresse'),
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='rechnungsadresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Rechnungsadresse', to='mitglieder.Adresse'),
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='wohnadresse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Wohnadresse', to='mitglieder.Adresse'),
        ),
    ]
