# Generated by Django 2.1.3 on 2018-12-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0009_auto_20181204_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vereinsmitglied',
            options={'ordering': ['sub']},
        ),
        migrations.RemoveField(
            model_name='vereinsmitglied',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vereinsmitglied',
            name='nachname',
        ),
        migrations.RemoveField(
            model_name='vereinsmitglied',
            name='vorname',
        ),
    ]
