# Generated by Django 2.1.3 on 2018-12-10 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mitglieder', '0010_auto_20181210_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vereinsmitglied',
            options={'ordering': ['last_name']},
        ),
        migrations.RemoveField(
            model_name='vereinsmitglied',
            name='id',
        ),
        migrations.AddField(
            model_name='vereinsmitglied',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
