# Generated by Django 2.1.3 on 2019-02-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0011_auto_20181210_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='vereinsmitglied',
            name='rechnung',
            field=models.FileField(blank=True, upload_to='invoices/'),
        ),
    ]
