# Generated by Django 2.1.3 on 2019-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0012_vereinsmitglied_rechnung'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnent',
            name='rechnung',
            field=models.FileField(blank=True, upload_to='aboinvoices/'),
        ),
    ]
