# Generated by Django 2.0.3 on 2019-11-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0013_abonnent_rechnung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboheft',
            name='heftanzahl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='institution',
            name='heftanzahl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='offeneposten',
            name='mitglied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.VereinsMitglied'),
        ),
        migrations.AlterField(
            model_name='vereinsmitglied',
            name='heftanzahl',
            field=models.IntegerField(default=0),
        ),
    ]
