# Generated by Django 2.0.3 on 2019-11-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0014_auto_20191129_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeneposten',
            name='institution',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.Institution'),
        ),
    ]
