# Generated by Django 2.1.3 on 2019-12-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0015_offeneposten_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='rechnung',
            field=models.FileField(blank=True, upload_to='invoices/'),
        ),
    ]
