# Generated by Django 2.0.3 on 2021-12-03 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0016_institution_rechnung'),
    ]

    operations = [
        migrations.CreateModel(
            name='offeneAboPosten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bezahltam', models.DateTimeField(blank=True, null=True)),
                ('offen', models.FloatField(default=0)),
                ('zahlung', models.FloatField(blank=True, default=0, null=True)),
                ('bezahlt', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('aboheft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mitglieder.AboHeft')),
            ],
            options={
                'ordering': ['erstellt'],
            },
        ),
    ]
