# Generated by Django 2.0.3 on 2023-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitglieder', '0017_offeneaboposten'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboheft',
            name='rechnung',
            field=models.FileField(blank=True, upload_to='invoices/'),
        ),
    ]
